# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bd664c0ec06c643aaba768917c21b89e48dff4782e49ed9798244c71391c8fddb141f59c4e29724efac09637047e884f436f72db4d7b766a4acc317904e9f23

test:
  secret_key_base: 4fee1d50bdd4e6d282dfeff5a09a10db85a8367475fe5519b9f274d57f3ce0a41b76f45b5c20be9cb9d545db66b234c471375ce64666ae7aecb34ee4bff5a9bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
